-- IRENG17 minimal non-secret seed for clean deployments.
-- Import after database/ireng17_schema.sql and php artisan migrate --force.
-- Replace API credentials in backoffice or via SQL before enabling game/payment traffic.

INSERT INTO `api` (
  `id`,
  `sg_agent_code`,
  `sg_sign`,
  `sg_endpoint`,
  `nx_agent_code`,
  `nx_token`,
  `nx_endpoint`,
  `wsg_agent_code`,
  `wsg_token`,
  `wsg_endpoint`,
  `ng_agent_code`,
  `ng_signature`,
  `ng_endpoint`,
  `sg_status`,
  `nx_status`,
  `ng_status`,
  `wsg_status`,
  `updated_at`
) VALUES (
  1,
  NULL,
  NULL,
  NULL,
  '',
  '',
  '',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  '0',
  '1',
  '0',
  '0',
  CURRENT_TIMESTAMP
)
ON DUPLICATE KEY UPDATE
  `nx_agent_code` = VALUES(`nx_agent_code`),
  `nx_token` = VALUES(`nx_token`),
  `nx_endpoint` = VALUES(`nx_endpoint`),
  `updated_at` = CURRENT_TIMESTAMP;

INSERT INTO `genral_settings` (
  `id`,
  `nama_web`,
  `telp`,
  `wa`,
  `tele`,
  `running_text`,
  `logo`,
  `popup`,
  `popup_bg`,
  `favicon`,
  `template`,
  `updated_at`,
  `live_chat`,
  `live_chat_js`,
  `msg_popup`,
  `themes`,
  `seo_banner`,
  `seo_meta_keywords`,
  `seo_description`,
  `seo_social_title`,
  `seo_social_description`,
  `maintenance_mode`,
  `deposit_delay`,
  `url_gateway`,
  `apikey_gateway`,
  `callback_url`,
  `qris_status`,
  `qris_image`,
  `minimal_depo`,
  `maksimal_wd`,
  `minimal_wd`
) VALUES (
  1,
  'ireng17',
  '',
  '',
  '',
  'Selamat datang di IRENG17.',
  NULL,
  NULL,
  '#000000',
  NULL,
  'main',
  NOW(),
  NULL,
  '',
  'Selamat datang di IRENG17. Pastikan data deposit dan withdraw sudah benar sebelum transaksi.',
  'midnight-pulse',
  NULL,
  'ireng17, slot online, game slot, deposit qris',
  'ireng17 adalah lobby game online dengan katalog slot, live casino, sportsbook, crash game, promo member, dan deposit cepat.',
  'IRENG17',
  'IRENG17 lobby game online dengan tampilan responsif dan katalog provider lokal.',
  0,
  0,
  NULL,
  NULL,
  NULL,
  0,
  NULL,
  20000,
  100000000,
  50000
)
ON DUPLICATE KEY UPDATE
  `nama_web` = VALUES(`nama_web`),
  `updated_at` = NOW();
